name: jellyfin

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:10.10.7
    restart: unless-stopped
    network_mode: bridge
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: America/Sao_Paulo
    ports:
      - "8097:8096"   # WebUI HTTP
      - "8921:8920"   # WebUI HTTPS
      - "7359:7359"   # Auto-discovery
      - "1901:1900"   # DLNA
    volumes:
      - /DATA/AppData/jellyfin/config:/config
      - /mnt/Se0/10-Mídias(Jellyfin):/Media
