name: big-bear-syncthing

services:
  syncthing:
    container_name: big-bear-syncthing
    image: syncthing/syncthing:2.0
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
    ports:
      - "8384:8384"       # WebUI
      - "22000:22000/tcp" # Sync TCP
      - "22000:22000/udp" # Sync UDP
      - "21027:21027/udp" # Discovery
    volumes:
      - /DATA/AppData/big-bear-syncthing/data:/var/syncthing
      - ${SYNC_DATA_PATH}:/media/data/syncthing
